# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0a3ca424d1836fdb89bd7ab6be58f18e890d4ebd9664476ce56be31dbd1fef8d39a32c23229583adaf1f1a2c9614c9af43f9f1519bc43d4eb789418fa0f5aa9

test:
  secret_key_base: 8b7ea4ef1cdc1304196b526d33443305e8ec6fd88297325c7015e9ef1df1365e26fe841111a03f7921bbbf5984b58d4ef68f30310ed03e00391b827bd07722ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
